#!/usr/bin/env python3
"""Reset the data generated by social_ingest.

This script clears the social analytics tables and resets the pipeline state on
reddit_posts so social_ingest can be rerun against the same deep-scanned raw data.
"""

import argparse
import os
import sys
from pathlib import Path

import psycopg2
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / ".env")


def build_connection():
    missing = [
        name for name in ("DB_NAME", "DB_USER", "DB_PASSWORD")
        if not os.getenv(name)
    ]
    if missing:
        raise RuntimeError(
            "Missing database environment variables: " + ", ".join(missing)
        )

    return psycopg2.connect(
        dbname=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        host=os.getenv("DB_HOST", "localhost"),
        port=int(os.getenv("DB_PORT", "5432")),
    )


def reset_social_data(dry_run=False):
    conn = build_connection()
    try:
        with conn.cursor() as cur:
            if dry_run:
                print("[dry-run] TRUNCATE social analytics tables")
                print("[dry-run] UPDATE reddit_posts SET pipeline_processed = FALSE WHERE deep_scanned = TRUE")
            else:
                cur.execute(
                    "TRUNCATE TABLE social_posts, social_relationships, social_entities, social_categories, social_meta RESTART IDENTITY CASCADE;"
                )
                cur.execute(
                    "UPDATE reddit_posts SET pipeline_processed = FALSE WHERE deep_scanned = TRUE;"
                )
                conn.commit()
                print("Reset complete: social analytics tables cleared and reddit_posts pipeline state reset.")
    finally:
        conn.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Reset social_ingest outputs")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the reset actions without changing the database",
    )
    args = parser.parse_args()

    try:
        reset_social_data(dry_run=args.dry_run)
    except Exception as exc:
        print(f"Reset failed: {exc}", file=sys.stderr)
        sys.exit(1)
